version: "2.17"
services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /db_storage:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis_storage:/var/lib/redis/data

volumes:
  db_storage:
  redis_storage:
