FROM gradle:7.6.1-jdk-alpine AS BUILD_STAGE
COPY --chown=gradle:gradle . /home/gradle
RUN gradle build || return 1

FROM openjdk:17-jdk-alpine
ENV APP_NAME=meetings-bot-1.0.0-SNAPSHOT.jar
ENV APP_HOME=/app
ENV TELEGRAM_USERNAME=$TELEGRAM_USERNAME
ENV TELEGRAM_TOKEN=$TELEGRAM_TOKEN
ENV TELEGRAM_WEBHOOK=$TELEGRAM_WEBHOOK
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE:dev,polling
COPY --from=BUILD_STAGE /home/gradle/build/libs/$APP_NAME $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT exec java -jar -DTELEGRAM_WEBHOOK=$TELEGRAM_WEBHOOK -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -DTELEGRAM_USERNAME=$TELEGRAM_USERNAME -DTELEGRAM_TOKEN=$TELEGRAM_TOKEN $APP_NAME
