version: "2.17"
services:
  dbpostgres:
    container_name: dbpostgres
    image: postgres:15.3
    environment:
      POSTGRES_DB: "meetsdb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
  rediscache:
    container_name: rediscache
    image: redis:7.0.11-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - /db_data:/var/lib/redis/data
