spring:
  profiles:
    default: dev,polling
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
telegram:
  bot:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}
    webHookPath: https://b38c-145-255-2-48.ngrok-free.app
    authorizePath: https://api.telegram.org/bot${telegram.bot.token}/setWebhook?url=${telegram.bot.webHookPath}
  meetings:
    startWorkDay: 9
    endWorkDay: 18
cache:
  redis:
    ttl:
      user: 30
      groupMembers: 10
  custom:
    ttl:
      meeting: 10
      bot: 30
application:
  locale: ru-RU
