spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetsdb
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
telegram:
  username: ${TELEGRAM_USERNAME}
  botToken: ${TELEGRAM_TOKEN}
redis:
  ttl:
    user: 60
    meeting: 1800
