spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetsdb
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
telegram:
  bot:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}
    webHookPath: https://b3b7-145-255-2-121.ngrok-free.app
    authorizePath: https://api.telegram.org/bot${telegram.bot.token}/setWebhook?url=${telegram.bot.webHookPath}
  meetings:
    startWorkDay: 9
    endWorkDay: 18
rediscache:
  ttl:
    user: 60
    groupMembers: 10
customcache:
  ttl:
    meeting: 30
    bot: 30
application:
  locale: ru-RU
