package com.ufanet.meetingsbot.state;

public enum MeetingState {
    GROUP_SELECTION,
    PARTICIPANTS_SELECTION,
    SUBJECT_SELECTION,
    QUESTION_SELECTION,
    DATE_SELECTION,
    TIME_SELECTION,
    TIME_DISCUSSION_SELECTION,
    ADDRESS_SELECTION,
    AWAITING,
    APPROVED,
    CANCELED
}
