name: project ci/cd flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run docker-compose
        run: docker-compose -f "docker-compose.yaml" up -d --build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew clean -q --stacktrace -PTELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} -PTELEGRAM_USERNAME=${{ secrets.TELEGRAM_USERNAME }} build

#    - name: Build and push
#      uses: docker/build-push-action@v3
#      with:
#        context: .
#        build-args: |
#          "TELEGRAM_USERNAME=${{ secrets.TELEGRAM_USERNAME }}"
#          "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}"
