name: project ci/cd flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_USERNAME: ${{ secrets.TELEGRAM_USERNAME }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setting environment variables
        run: |
          truncate -s 0 .env 
          echo TELEGRAM_USERNAME="${{ secrets.TELEGRAM_USERNAME }}"$'\n'TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" >> .env 

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aanailevich/meetings-bot
          tags: latest
          registry: docker.io
          buildArgs:
            BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }},BOT_USERNAME=${{ secrets.TELEGRAM_USERNAME }}
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

